theme: jekyll-theme-cayman

#setup
title: hello world
description: Easily offer bundled products with discouns on your store. Bundled Discounts Plugin for nopCommerce enables the store owner to enhance sales by offering discounts on purchase of additional products along with the one that customer wants to buy.
baseurl: ""
paginate: 1
values: 
  layout: single

# About/contact

Author: Prashant Bhargava
